absensi_guru/urls.py
from django.contrib import admin
from django.urls import path, include
from absen.views import *
from face_detection.views import *
from laporan.views import *
from django.contrib.auth.views import LoginView, LogoutView
from userauth.views import add_user, delete_user
from django.conf.urls.static import static
from absen.viewset_api import *
from laporan.viewset_api import *
from rest_framework import routers
from administrator.views import *

router = routers.DefaultRouter()
router.register('showabsen', PresenceViewset, basename='Presence')
router.register('presence/checkin', CheckinViewset, basename='CheckinRecord')
router.register('presence/checkout', CheckoutViewset, basename='CheckoutRecord')
router.register('presence/days', DaysViewset, basename='Days')
router.register('classes', ClassViewset)
router.register('subjects', SubjectViewset)
router.register('laporan/belajar', StudyReportViewset, basename='StudyReport')
router.register('laporan/bimbingan', GuidanceReportViewset, basename='GuidanceReport')
router.register('laporan/pengembangan', HumanDevelopmentReportViewset, basename='HumanDevelopmentReport')
router.register('laporan/karya-inovatif', InnovativeWorkReportViewset, basename='InnovativeWorkReport')
router.register('laporan/karya-ilmiah', ScientificWorkReportViewset, basename='ScientificWorkReport')
router.register('laporan/tugas-lainnya', DutyReportViewset, basename='DutyReport')
router.register('users', EmployeeViewset, basename='Users')


urlpatterns = [
    path('api/', include(router.urls)),
    path('', LoginView.as_view(), name='index'),
    path('absen/', absen, name='absen'),
    path('face_detection/detect/', detect),
    path('login/', LoginView.as_view(), name='login' ),
    path('logout/', LogoutView.as_view(next_page='/login'), name='logout'),
    path('delete-user/<int:id_user>',delete_user, name='delete_user'),
    path('absen/show', show_absen, name="show_absen"),
    path('laporan/belajar/add', study_report, name='study_report'),
    path('laporan/bimbingan/add', guidance_report, name='guidance_report'),
    path('laporan/karya-ilmiah/add', scientific_work_report, name='scientific_work_report'),
    path('laporan/karya-inovatif/add', innovative_work_report, name='innovative_work_report'),
    path('laporan/pengembangan-diri/add', human_development_report, name='human_development_report'),
    path('laporan/tugas-lainnya/add', duty_report, name='duty_report'),
    path('laporan/belajar/show', show_study_report, name='show_study_report'),
    path('laporan/bimbingan/show', show_guidance_report, name='show_guidance_report'),
    path('laporan/karya-ilmiah/show', show_scientific_work_report, name='show_scientific_work_report'),
    path('laporan/karya-inovatif/show', show_innovative_work_report, name='show_innovative_work_report'),
    path('laporan/pengembangan-diri/show', show_human_development_report, name='show_human_development_report'),
    path('laporan/tugas-lainnya/show', show_duty_report, name='show_duty_report'),
    path('admin/dashboard', show_dashboard_admin, name='show_dashboard_admin'),
    path('admin/rekap-absen', show_absen_admin, name='show_absen_admin'),
    path('admin/rekap-laporan', show_laporan_admin, name='show_laporan_admin'),
    path('admin/user-list', show_users_admin, name='show_users_admin'),
    path('admin/add-user', add_user, name='add_user_admin'),
    path('admin/add-user-bulk', add_user_bulk, name='add_user_bulk'),
    path('admin/undo-add-user-bulk', undo_add_user_bulk, name='undo_add_user_bulk'),
    path('admin/edit-password/<int:id_user>', edit_password_admin, name='edit_password'),
    path('admin/edit-role/<int:id_user>', edit_role_admin, name='edit_role'),
]

# path('admin/', admin.site.urls),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.

userauth/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    nip = models.CharField(max_length=18, null=True, blank=True)
    full_name = models.CharField(max_length=255,null=True)
    position = models.CharField(max_length=100,null=True)
    # photo = models.ImageField(upload_to='profile/', null=True)
    

class Days(models.Model):
    employee_id = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)

administrator/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group, User
from userauth.models import Days, Employee
from django.contrib import messages
import csv
from django.conf import settings
import logging
from absensi_guru import forms
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm



# Create your views here.
logging.basicConfig(level=logging.NOTSET)
@login_required
@staff_member_required
def show_absen_admin(request):
    return render(request, 'absen-admin.html')

@login_required
@staff_member_required
def show_dashboard_admin(request):
    return render(request, 'dashboard-admin.html')

@login_required
@staff_member_required
def show_laporan_admin(request):
    return render(request, 'laporan-admin.html')

@login_required
@staff_member_required
def show_users_admin(request):
    is_action = request.GET
    user_id = is_action.get('edit') if is_action.get('edit') != None else is_action.get('delete')
    
    if is_action:
        if is_action.get('delete') != None:
            user = User.objects.get(employee__id=user_id)
            user.delete()
            return render(request, 'users-admin.html')
        
        elif is_action.get('edit') != None:
            credential = User.objects.get(employee__id=user_id)
            employee = Employee.objects.get(id=user_id)
            days = Days.objects.get(employee_id=user_id)
            
            if request.POST:
                credential_form = forms.EditCredentialForm(request.POST, instance=credential)
                employee_form = forms.EditEmployeeForm(request.POST, instance=employee)
                days_form = forms.DaysForm(request.POST, instance=days)
                print(credential_form.errors)
                
                if credential_form.is_valid() and employee_form.is_valid() and days_form.is_valid():
                    credential_form_f = credential_form.save(commit=False)
                    first_name = request.POST.get('full_name').split(' ')
                    first_name.pop()
                    first_name = ' '.join(first_name)
                    credential_form_f.first_name = first_name
                    credential_form_f.last_name = request.POST.get('full_name').split()[-1]
                    
                    credential_form_f.save()
                    
                    employee_form.save()
                    
                    days_form.save()
                    
                    return redirect('show_users_admin')
                
                elif not credential_form.is_valid():
                    context = {
                        'credential_form': forms.EditCredentialForm(instance=credential),
                        'employee_form': forms.EditEmployeeForm(instance=employee),
                        'days_form': forms.DaysForm(instance=days),
                        'message': "Gagal menyunting pengguna, username atau password tidak tersedia",
                        "user_id": user_id
                    }
                
                    return render(request, 'edit-user-admin.html', context)
                
                else:
                    context = {
                        'credential_form': forms.EditCredentialForm(instance=credential),
                        'employee_form': forms.EditEmployeeForm(instance=employee),
                        'days_form': forms.DaysForm(instance=days),
                        'message': "Gagal menyunting pengguna, pastikan data terisi dengan benar",
                        "user_id": user_id
                    }
                
                    return render(request, 'edit-user-admin.html', context)
                    
                    
            else:
                context = {
                        'credential_form': forms.EditCredentialForm(instance=credential),
                        'employee_form': forms.EditEmployeeForm(instance=employee),
                        'days_form': forms.DaysForm(instance=days),
                        'user_id': user_id
                    }
                return render(request, 'edit-user-admin.html', context)
            
            
    return render(request, 'users-admin.html')

@login_required
@staff_member_required
def add_user_bulk(request):
    with open(settings.MEDIA_ABS_PATH + '/foreign/user_absen_sija.csv') as users:
        users = csv.reader(users, delimiter=';')
        for user in users:
            User.objects.create(
                username=user[0],
                first_name=user[2],
                last_name=user[3],
                password=make_password(user[1])
            )
            
            Employee.objects.create(
                user_id=User.objects.latest('id').id,
                full_name=user[2] + ' ' + user[3],
                position=user[4]
            )
            
            Days.objects.create(
                monday=user[6],
                tuesday=user[7],
                wednesday=user[8],
                thursday=user[9],
                friday=user[10],
                employee_id=Employee.objects.latest('id')
            )
            
            group = Group.objects.get(name=user[5])
            group.user_set.add(User.objects.latest('id'))
            
    return render(request, 'bulk-add-users-admin.html')

@login_required
@staff_member_required
def undo_add_user_bulk(request):
    # Bulk Delete for emergency
    users = User.objects.filter(username__contains='smk')
    for user in users:
        user.delete()
            
    return render(request, 'undo-bulk-add-users-admin.html')

@login_required
@staff_member_required
def edit_password_admin(request, id_user):
    user = User.objects.get(employee__id=id_user)
    
    if request.POST:
        print(request.POST.get('password'))
        user.password = make_password(request.POST.get('password'))
        user.save()
        return redirect('show_users_admin')
        
    else:
        return render(request, 'edit-password-user-admin.html')
    
@login_required
@staff_member_required
def edit_role_admin(request, id_user):
    user = User.objects.get(employee__id=id_user)
    
    if request.POST:
        user.groups.clear()
        group = Group.objects.get(name=request.POST.get('group'))
        group.user_set.add(user)
        return redirect('show_users_admin')
    
    else:
        return render(request, 'edit-role-user-admin.html', {"form": forms.RoleForm(request.POST)})
    

administrator/templates/absen-admin.html
{% extends 'base-admin.html' %}
{% load static %}
{% block title %}
    <title>Rekap Absen</title>
{% endblock title %}

{% block content %}

{% include 'sidebar-admin.html' %}
{% include 'loading.html' %}
    <section class="container-admin">
        <section class="content loading">
            <div class="action">
                {% include 'button-search.html' %}
                {% include 'button-filter.html' %}
                {% include 'button-print.html' %}
            </div>
            <div class="table">
                <table>
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tanggal</th>
                            <th>Nama</th>
                            <th>NIP</th>
                            <th>Jam Masuk</th>
                            <th>Bukti Masuk</th>
                            <th>Jam Keluar</th>
                            <th>Bukti Keluar</th>
                            <th>Keterangan Masuk</th>
                            <th>Keterangan Keluar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for=" (data,index) in dataFetchedAttendance ">
                            <td>[[ index + 1 ]]</td>
                            <td>[[ data.presence_date ]]</td>
                            <td>[[ data.fullName ]]</td>
                            <td>[[ data.nip ]]</td>
                            <td>[[ data.checkin_time ]]</td>
                            <td>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                    :data-bs-target="' #attendIn-doc-' + index">
                                    Lihat Bukti
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" :id= " 'attendIn-doc-' + index" data-bs-backdrop="static"
                                    data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">Bukti Masuk</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <img v-bind:src="data.checkin_img" alt="">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-primary">Understood</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>[[ data.checkout_time ]]</td>
                            <td>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                    :data-bs-target="'#attendOut-doc-' + index ">
                                    Lihat Bukti
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" :id="'attendOut-doc-' + index " data-bs-backdrop="static"
                                    data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">Bukti Keluar</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <img v-bind:src="data.checkout_img" alt="">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>[[ data.checkin_desc ]]</td>
                            <td>[[ data.checkout_desc ]]</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
    </section>
{% endblock content%}
{% block opt_script %}
    
    <script type="text/javascript">
        showAttendAdmin()
    </script>

{% endblock %}

administrator/templates/add-admin.html
{% extends 'base-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
<title>Add User</title>
{% endblock title %}

{% block content %}

{% include 'sidebar-admin.html' %}
<section class="container-admin">
    <section class="content">
        <form action="{% url 'add_user_admin' %}" method="post" class="add-user">
            {% csrf_token %}
            {% comment %} <div class="form-floating">
                <input type="text" class="form-control" id="floating-username" placeholder="Hermawan123" name="username"
                    required>
                <label for="floating-username">Username</label>
                <div class="info">
                    <p>Wajib diisi. 150 karakter atau kurang. huruf, angka dan @/./+/-/_ saja.</p>
                </div>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floating-name" placeholder="Hermawan Fanreza"
                    name="fullname" required>
                <label for="floating-name">Nama Lengkap</label>
            </div>
            <div class="form-floating">
                <input type="tel" class="form-control" id="floating-nip" placeholder="21831298" name="nip">
                <label for="floating-nip">NIP</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floating-posisi"
                    placeholder="Wakil Kepala Sekolah Bidang Kurikulum" name="position" required>
                <label for="floating-posisi">Posisi</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="floating-password" placeholder="Hermawan Fanreza"
                    name="password" required>
                <label for="floating-password">Password</label>
                <div class="info">
                    <ul>
                        <li>Password harus mengandung setidaknya 8 karakter</li>
                        <li>Password tidak boleh sepenuhnya menggunakan angka</li>
                    </ul>
                </div>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="floating-password-confirm"
                    placeholder="Hermawan Fanreza" name="password-confirm" required>
                <label for="floating-password-confirm">Konfirmasi Password</label>
                <div class="info">
                    <p>Masukan password yang sama seperti sebelumnya</p>
                </div>
            </div>
            <div class="role">
                <header>Pilih Role</header>
                <div class="input">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault1" required>
                        <label class="form-check-label" for="flexRadioDefault1">
                            Admin
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault2" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Supervisor
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault3" checked>
                        <label class="form-check-label" for="flexRadioDefault3">
                            User
                        </label>
                    </div>
                </div>
            </div>
            <div class="day-work">
                <header>Piih Hari Kerja</header>
                <div class="input">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked1" name="days"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked1">
                            Senin
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked2" name="fays"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked2">
                            Selasa
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked3" name="days"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked3">
                            Rabu
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked4" name="days"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked4">
                            Kamis
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked5" name="days"
                            checked>
                        <label class="form-check-label" for="flexCheckChecked5">
                            Jumat
                        </label>
                    </div>
                </div>
            </div>
            <button type="submit" class="submit">Submit</button> {% endcomment %}
            {% if message %}
            {% if message == "Berhasil menambahkan pengguna" %}
            <div class="alert alert-success">{{ message }}</div>
            {% else %}
            <div class="alert alert-danger">{{ message }}</div>
            {% endif %}
            {% endif %}

            <div class="form-floating">
                {% comment %} <input type="text" class="form-control" id="floating-username" placeholder="Hermawan123"
                    name="username" required> {% endcomment %}
                {{credential_form.username}}
                <label for="floating-username">Username*</label>
                <div class="info">
                    <p>Wajib diisi. 150 karakter atau kurang. huruf, angka dan @/./+/-/_ saja.</p>
                </div>
            </div>
            <div class="form-floating">
                {% comment %} <input type="text" class="form-control" id="floating-name" placeholder="Hermawan Fanreza"
                    name="fullname" required> {% endcomment %}
                {{employee_form.full_name}}
                <label for="floating-name">Nama Lengkap*</label>
            </div>
            <div class="form-floating">
                {% comment %} <input type="tel" class="form-control" id="floating-nip" placeholder="21831298"
                    name="nip"> {% endcomment %}
                {{employee_form.nip}}
                <label for="floating-nip">NIP</label>
            </div>
            <div class="form-floating">
                {% comment %} <input type="text" class="form-control" id="floating-posisi"
                    placeholder="Wakil Kepala Sekolah Bidang Kurikulum" name="position" required> {% endcomment %}
                {{employee_form.position}}
                <label for="floating-posisi">Posisi*</label>
            </div>
            <div class="form-floating">
                {% comment %} <input type="password" class="form-control" id="floating-password"
                    placeholder="Hermawan Fanreza" name="password" required> {% endcomment %}
                {{credential_form.password1}}
                <label for="floating-password">Password*</label>
                <div class="info">
                    <ul>
                        <li>Password harus mengandung setidaknya 8 karakter</li>
                        <li>Password tidak boleh sepenuhnya menggunakan angka</li>
                    </ul>
                </div>
            </div>
            <div class="form-floating">
                {% comment %} <input type="password" class="form-control" id="floating-password-confirm"
                    {% endcomment %} {% comment %} placeholder="Hermawan Fanreza" name="password-confirm" required>
                {% endcomment %}
                {{credential_form.password2}}
                <label for="floating-password-confirm">Konfirmasi Password*</label>
                <div class="info">
                    <p>Masukan password yang sama seperti sebelumnya</p>
                </div>
            </div>
            <div class="role">
                {% comment %} <div class="input">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault1" required>
                        <label class="form-check-label" for="flexRadioDefault1">
                            Admin
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault2" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Supervisor
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="role" id="flexRadioDefault3" checked>
                        <label class="form-check-label" for="flexRadioDefault3">
                            User
                        </label>
                    </div>
                </div> {% endcomment %}
                {{employee_form.group | as_crispy_field}}
            </div>
            <div class="day-work">
                <header>Piih Hari Kerja*</header>
                <div class="input">
                    <div class="form-check">
                        {% comment %} <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked1"
                            name="days" checked> {% endcomment %}
                        {{days_form.monday}}
                        <label class="form-check-label" for="id_monday">
                            Senin
                        </label>
                    </div>
                    <div class="form-check">
                        {% comment %} <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked2"
                            name="days" checked> {% endcomment %}
                        {{days_form.tuesday}}
                        <label class="form-check-label" for="id_tuesday">
                            Selasa
                        </label>
                    </div>
                    <div class="form-check">
                        {% comment %} <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked3"
                            name="days" checked> {% endcomment %}
                        {{days_form.wednesday}}
                        <label class="form-check-label" for="id_wednesday">
                            Rabu
                        </label>
                    </div>
                    <div class="form-check">
                        {% comment %} <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked4"
                            name="days" checked> {% endcomment %}
                        {{days_form.thursday}}
                        <label class="form-check-label" for="id_thursday">
                            Kamis
                        </label>
                    </div>
                    <div class="form-check">
                        {% comment %} <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked5"
                            name="days" checked> {% endcomment %}
                        {{days_form.friday}}
                        <label class="form-check-label" for="id_friday">
                            Jumat
                        </label>
                    </div>

                </div>
            </div>
            <div class="button-group-form">
                <a href="" class="cancel"> Batal</a>
                <button type="submit" class="submit">Submit</button>
            </div>
        </form>
    </section>
</section>
{% endblock content %}

administrator/templates/bulk-add-users-admin.html
<p>Import success</p>

administrator/templates/dashboard-admin.html
{% extends 'base-admin.html' %}
{% load static %}
{% block title %}
    <title>Dashboard</title>
{% endblock title %}

{% block content %}

{% include 'sidebar-admin.html' %}
    <section class="container-admin">
        <section class="content">
            <div class="image">
                <p>Sedang Dalam Tahap Pembuatan, akan tersedia <span>segera</span></p>
                <img src="../../static/image/development.png" alt="">     
            </div>
        </section>
    </section>
{% endblock content %}

administrator/templates/edit-role-user-admin.html
{% extends 'base-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
<title>Edit Role</title>
{% endblock title %}

{% block content %}

{% include 'sidebar-admin.html' %}
<section class="container-admin">
    <section class="content">
        <form action="" method="post" class="add-user">
            {% csrf_token %}
            <div class="role">
                {{ form }}
            </div>

            <div class="button-group-form">
                <a href="" class="cancel"> Batal</a>
                <button type="submit" class="submit">Submit</button>
            </div>
        </form>
    </section>
</section>
{% endblock content %}

administrator/templates/undo-bulk-add-users-admin.html
<p>Undo Success</p>